[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "cancun"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
amoy = "${POLYGON_AMOY_RPC_URL}"
anvil = "http://127.0.0.1:8545"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
amoy = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
